<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Annium.Execution.Background" Version="1.1.24" />
    <PackageVersion Include="Annium.Logging.Console" Version="1.1.24" />
    <PackageVersion Include="Annium.Net.Servers.Web" Version="1.1.24" />
    <PackageVersion Include="Annium.Core.Entrypoint" Version="1.1.24" />
    <PackageVersion Include="Annium.Configuration.Yaml" Version="1.1.24" />
    <PackageVersion Include="Annium.Core.DependencyInjection" Version="1.1.24" />
    <PackageVersion Include="Annium.Core.Runtime" Version="1.1.24" />
    <PackageVersion Include="Annium.Net.Http" Version="1.1.24" />
    <PackageVersion Include="Annium.NodaTime.Serialization.Json" Version="1.1.12" />
    <PackageVersion Include="Annium.Serialization.Json" Version="1.1.24" />
    <PackageVersion Include="Annium.Testing" Version="1.1.24" />
    <PackageVersion Include="OpenAI" Version="2.7.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Microsoft.SemanticKernel" Version="1.67.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.12.19" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="0.3.0-preview.4" />
    <PackageVersion Include="ModelContextProtocol.Core" Version="0.3.0-preview.4" />
    <PackageVersion Include="System.Text.Json" Version="9.0.5" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="xunit.v3" Version="3.2.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
